# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Elisa Music Player"
SPDX-PackageSupplier = "Matthieu Gallien <matthieu_gallien@yahoo.fr>"
SPDX-PackageDownloadLocation = "https://invent.kde.org/multimedia/elisa"

[[annotations]]
path = ".flatpak-manifest.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Tobias Fella <tobias.fella@kde.org>"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = ".gitlab/merge_request_templates/Default.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Nate Graham <nate@kde.org>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "android/res/drawable/vendor_logo.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014 Andrew Lake <jamboarder@gmail.com>"
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = ["android/play_store_512.png", "android/res/mipmap**/**background.png", "android/res/mipmap**/**foreground.png", "android/res/mipmap**/ic_launcher.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Paul Lesur <paul.lesur@free.fr>"
SPDX-License-Identifier = "LGPL-3.0-or-later"

[[annotations]]
path = "android/res/mipmap**/**monochrome.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "Janet Blackquill <uhh.add@gmail.com>"
SPDX-License-Identifier = "LGPL-3.0-or-later"
